; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "NuclearRT"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "shishkabob"
#define MyAppURL "https://nuclearrt.com/"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{82E4CF7D-B1CC-4557-AEE4-91D9DEFBEAEA}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\Program Files (x86)\Steam\steamapps\common\Clickteam Fusion 2.5\Data\Runtime
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=nuclearrt_{#MyAppVersion}_installer
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "D:\development\nuclearrt-alpha\build\runtime\*"; DestDir: "{app}/NuclearRT/runtime"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\development\nuclearrt-alpha\build\exporter\*"; DestDir: "{app}/NuclearRT/exporter"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\development\nuclearrt-alpha\build\nuclearrt.bld"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

